[Settings]
ImeIndicatorEnabled=1
StartupLayout=FMIX12x-Minato[Built-in]
HoldTh=300
LayerHoldTh=150 ;Layers.HoldThに設定される
b_time=50
LogEnabled=0
MaxLog=5000
space=NAVI_CTRL
noconv=SHORTCUT_CTRL
b_time2=50

[2]
ver=2
Name=FMIX13f2-Minato2
Layout=FMIX13f2
LayoutIME=Minato2

[3]
ver=2 ;ver2の利用を推奨
Name=FMIX13f3-Minato3
Layout=FMIX13f3
LayoutIME=Minato3

[FMIX13f]
Mode=1 ;LKeyのモード指定
L00= 1 2 3 4 5 6 7 8 9 0 - ^ \
L01= q w r f k y l u p {sc027} @ [
L02= a s d t g h n e i o : ]
L03= z x c v b j m , . / \

[FMIX13f2]
Mode=4 ;LKeyのモード指定
L00= 1 2 3 4 5 6 7 8 9 0 - ^ \
L01= q w e r f [ y l u p {sc027} @
L02= a s d t g ] h n i e o :
L03= z x c v b k j m , . /

[FMIX13f3]
Mode=4 ;LKeyのモード指定
L00= 1 2 3 4 5 6 7 8 9 0 - ^ \
L01= q w r f k @ [ y l u p {sc027}
L02= a s d t g : ] h n e i o 
L03= z x c v b / \ j m , .

[Minato2]
Mode=4 ;LKeyのモード指定
L00= 1 2 3 4 5 6 7 8 9 0 - ^ \
L01= q w d r f [ v yu u yo {sc027} @ 
L02= n s k t g ] nn a i e o :
L03= z p m h b \ - ya , . /
m_s_Pf = 7,ite,{BS}ta
m_s_r = 7,uru,{BS}{BS}sareru

[Minato3]
Mode=4 ;LKeyのモード指定
L00= 1 2 3 4 5 6 7 8 9 0 - ^ \
L01= q w r d f @ [ v yu u yo {sc027} 
L02= n s k t g : ] nn a i e o
L03= z p m h b \ / - ya , .

[Kanade]
Mode=4 ;LKeyのモード指定
L00=1 2 3 4 5 6 7  8 9  0 - ^ \
L01=q w r p l f yu u yo - @ [
L02=k s t n h {sc027} a  i e  o : ]
L03=g z d m b j m  , .  / \
S00=1 2 3 4 5 6 7   8  9  0 - ^ \
S01=q w r p l f yu  u  yo - @ [
S02=k s t n h {sc027} ya  xi xe o : ]
S03=[ ] d m b j ltu ,  .  / \
m_r+p=7,areru
[NAVI_CTRL]
one = {Blind}{F1}
two = {Blind}{F2}
three = {Blind}{F3}
four = {Blind}{F4}
five = {Blind}{F5}
six = {Blind}{F6}
seven = {Blind}{F7}
eight = {Blind}{F8}
nine = {Blind}{F9}
zero = {Blind}{F10}
minus = {Blind}{F11}
hat = {Blind}{F12}
yen = ^+{sc07D}
z = {Blind}^{z}
x = {Blind}^{x}
c = {Blind}^{c}
v = {Blind}^{v}
b = {Blind}^{z}
y = {Blind}^{z}
i = {Blind}{Backspace}
o = {Blind}{Up}
p = {Blind}{PgUp}
at = {Blind}{PgDn}
;at = {Blind}^{Home}
;openbracket = {Blind}^{End}
j = {Blind}{Home}
k = {Blind}{Left}
l = {Blind}{Down}
semicolon = {Blind}{Right}
closebracket = {Blind}{Enter}
;closebracket = ^+{sc07D}
m = {Blind}{End}
comma = {Blind}{Delete}
period = {Blind}^{Left}
slash = {Blind}^{Right}
;slash = ^+{sc07D}
enter = {Blind}+{Enter}
a = {Blind}^a

[SELECT]
one = ^z
two = ^x
three = ^c
four = ^v
z = ^z
x = ^x
c = ^c
v = ^v
b = ^z
y = ^y
u = {Backspace}
i = +{Up}
o = +{PgUp}
p = +{PgDn}
at = ^+{Home}
openbracket = ^+{End}
h = +{Home}
j = +{Left}
k = +{Down}
l = +{Right}
semicolon = +{Enter}
enter = {Blind}{Enter}
n = +{End}
m = {Delete}
comma = ^+{Left}
period = ^+{Right}
space = {Backspace}
up = +{Up}
left = +{Left}
down = +{Down}
right = +{Right}

[SYMBOL_NUM]
one = {Blind}{F1}
two = {Blind}{F2}
three = {Blind}{F3}
four = {Blind}{F4}
five = {Blind}{F5}
six = {Blind}{F6}
seven = {Blind}{F7}
eight = {Blind}{F8}
nine = {Blind}{F9}
zero = {Blind}{F10}
minus = {Blind}{F11}
hat = {Blind}{F12}
q = ?
w = {Blind}/
e = {Blind}{NumpadMult}
r = {Blind}{NumpadAdd}
t = +F3
a = (
s = )
d = _
f = {Blind}-
g = =
y = {Blind}{Backspace}
u = {Numpad7}
i = {Numpad8}
o = {Numpad9}
p = +^p
h = =
j = {Numpad0}
k = {Numpad1}
l = {Numpad2}
semicolon = {Blind}{Enter}
n = +3
m = {Numpad3}
comma = {Numpad4}
period = {Numpad5}
slash = {Numpad6}
z = [
x = ]
c = +[
v = +]
b = {sc073}
space = {Blind}{Backspace}

[SYMBOL1]
one = {Blind}{F1}
two = {Blind}{F2}
three = {Blind}{F3}
four = {Blind}{F4}
five = {Blind}{F5}
six = {Blind}{F6}
seven = {Blind}{F7}
eight = {Blind}{F8}
nine = {Blind}{F9}
zero = {Blind}{F10}
minus = {Blind}{F11}
hat = {Blind}{F12}
q = ?
w = {Blind}/
e = {Blind}{NumpadMult}
r = {Blind}{NumpadAdd}
t = +F3
a = (
s = )
d = _
f = {Blind}-
g = =
y = {Blind}{Backspace}
u = {Numpad7}
i = {Numpad8}
o = {Numpad9}
p = +^p
h = =
j = {Numpad0}
k = {Numpad1}
l = {Numpad2}
semicolon = {Blind}{Enter}
n = +3
m = {Numpad3}
comma = {Numpad4}
period = {Numpad5}
slash = {Numpad6}
z = +[
x = +]
c = [
v = ]
b = {sc073}
space = {Backspace}

[NUMPAD]
six = {Escape}
t = {Blind}{NumpadAdd}
a = (
s = )
f = -
g = =
seven = {Numpad7}
eight = {Numpad8}
nine = {Numpad9}
zero = {Blind}{NumpadMult}
minus = {Blind}{NumpadSub}
hat = {sc00D}
yen = \
y = {Backspace}
u = {Numpad4}
i = {Numpad5}
o = {Numpad6}
p = {Blind}{NumpadAdd}
at = {Blind}{Up}
h = =
j = {Numpad1}
k = {Numpad2}
l = {Numpad3}
semicolon = {Blind}{Left}
colon = {Blind}{Down}
closebracket = {Blind}{Right}
n = {Delete}

[SYMBOL2]
q = +1
w = +2
e = +3
r = +4
t = +5
a = +6
s = +7
d = {sc00D}
g = +@
z = ~
x = @
c = :
v = |
b = \

[SHIFT]
one = {Blind}{F1}
two = {Blind}{F2}
three = {Blind}{F3}
four = {Blind}{F4}
five = {Blind}{F5}
six = {Blind}{F6}
seven = {Blind}{F7}
eight = {Blind}{F8}
nine = {Blind}{F9}
zero = {Blind}{F10}
minus = {Blind}{F11}
hat = {Blind}{F12}
colon = +sc028
closebracket = +]

[SHORTCUT_CTRL]
a=^a
s=^s
c=^c
v=^v

