[Settings]
ImeIndicatorEnabled=1
StartupLayout=FMIX13f-Minato
long_press_th=300
LogEnabled=0
MaxLog=5000

[1]
;ver = 1 ver2の利用を推奨
Name=FMIX13f-Minato
; 30文字のアルファベット・記号
Layout=qwfrkylup;asdtghneiozxcvbjm,./
; 11文字の数字列
Num=1234567890-
; (オプション) IME ON時のレイアウト
ImeLayout=qwdrfylup;asktghneiozxcvbjm,./
ImeNum=1234567890-

[2]
ver = 2
Name=FMIX13-Kanade
L00= 1 2 3 4 5 6 7 8 9 0 - ^ \
L01= q w r l k y f u p ; @ [
L02= a s d t g h n e i o : ]
L03= z x c v b j m , . / \

I00= 1 2 3 4 5 6 7  8 9  0 - ^ \
I01= q w r p l f yu u yo - @ [
I02= k s t n h ; a  i e  o : ]
I03= g z d m b j m  , .  / \

IS00= 1 2 3 4 5 6 7   8  9  0 - ^ \
IS01= q w r p l f yu  u  yo - @ [
IS02= k s t n h ; ya  xi xe o : ]
IS03= [ ] d m b j ltu ,  .  / \


[3]
ver = 2
Name=FMIX13f-Kanade
L00= 1 2 3 4 5 6 7 8 9 0 - ^ \
L01= q w r f k y l u p ; @ [
L02= a s d t g h n e i o : ]
L03= z x c v b j m , . / \

I00= 1 2 3 4 5 6 7 8 9 0 - ^ \
I01= q w r d f ya yu u yo ; @ [
I02= a s k t g h n e i o : ]
I03= z p c v b j m , . / \

IS00= 1 2 3 4 5 6 7   8  9  0 - ^ \
IS01= q w r p l f yu  u  yo - @ [
IS02= k s t n h ; ya  xi xe o : ]
IS03= [ ] d m b j ltu ,  .  / \

[NAVI_CTRL]
[SYMBOL_NUM]
[SYMBOL1]
[SYMBOL2]
[SELECT]
[NUMPAD]
